<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da12_shape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DataFrame의 모양(shape) 변경

wide(column이 많은) DF <---> long(row이 많은) DF

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

# stack vs unstack

In [2]:
df = pd.DataFrame(data=np.arange(1, 7).reshape((2, 3)),
                  columns=['a', 'b', 'c'],
                  index=['X', 'Y'])
df

   a  b  c
X  1  2  3
Y  4  5  6

In [3]:
df_stacked = df.stack()  #> 컬럼의 이름들이 행 인덱스로 설정. stack: column --> row
df_stacked

X  a    1
   b    2
   c    3
Y  a    4
   b    5
   c    6
dtype: int64

In [4]:
df_stacked.index.nlevels

2

In [7]:
df_unstack1 = df_stacked.unstack()  #> 행 인덱스가 컬럼 이름으로 변환. row ---> column
df_unstack1

   a  b  c
X  1  2  3
Y  4  5  6

In [9]:
df_unstack2 = df_stacked.unstack(level=0)  # 첫번째 레벨의 행 인덱스가 컬럼 이름으로 변환.
df_unstack2

   X  Y
a  1  4
b  2  5
c  3  6