<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da14_movielens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Movielens 데이터 분석

# Imports

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 데이터 준비

In [2]:
# 데이터 파일들의 github 경로
movies_file = 'https://github.com/wesm/pydata-book/raw/refs/heads/3rd-edition/datasets/movielens/movies.dat'
ratings_file = 'https://github.com/wesm/pydata-book/raw/refs/heads/3rd-edition/datasets/movielens/ratings.dat'
users_file = 'https://github.com/wesm/pydata-book/raw/refs/heads/3rd-edition/datasets/movielens/users.dat'

In [3]:
# 각각의 데이터프레임에서 사용할 컬럼 이름들
movies_columns = ['movie_id', 'title', 'genres']
ratings_columns = ['user_id', 'movie_id', 'rating', 'timestamp']
users_columns = ['user_id', 'gender', 'age', 'occupation', 'zip_code']

## 데이터프레임 생성

*   movies
*   ratings
*   users
*   데이터프레임 합치기(merge)
    *   ratings와 movies를 merge(inner join)
    *   위의 결과와 users를 merge(inner join)

### movies 데이터프레임

In [4]:
movies = pd.read_csv(movies_file, names=movies_columns, sep='::', engine='python')

In [5]:
movies.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  3883 non-null   int64
 1   title     3883 non-null   object
 2   genres    3883 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.1+ KB

### ratings 데이터프레임

In [7]:
ratings = pd.read_csv(ratings_file, names=ratings_columns, sep='::', engine='python')

In [8]:
ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [9]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1000209 non-null  int64
 1   movie_id   1000209 non-null  int64
 2   rating     1000209 non-null  int64
 3   timestamp  1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB

In [10]:
# timestamp(정수) 컬럼 --> 날짜/시간(datetime) 타입으로 변환.
pd.to_datetime(ratings.timestamp, unit='s')  # unit: 's', 'ms', 'ns'

0         2000-12-31 22:12:40
1         2000-12-31 22:35:09
2         2000-12-31 22:32:48
3         2000-12-31 22:04:35
4         2001-01-06 23:38:11
                  ...
1000204   2000-04-26 02:35:41
1000205   2000-04-25 23:21:27
1000206   2000-04-25 23:19:06
1000207   2000-04-26 02:20:48
1000208   2000-04-26 02:19:29
Name: timestamp, Length: 1000209, dtype: datetime64[ns]

### users 데이터프레임

In [11]:
users = pd.read_csv(users_file, names=users_columns, sep='::', engine='python')

In [12]:
users.head()

   user_id gender  age  occupation zip_code
0        1      F    1          10    48067
1        2      M   56          16    70072
2        3      M   25          15    55117
3        4      M   45           7    02460
4        5      M   25          20    55455

In [13]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     6040 non-null   int64
 1   gender      6040 non-null   object
 2   age         6040 non-null   int64
 3   occupation  6040 non-null   int64
 4   zip_code    6040 non-null   object
dtypes: int64(3), object(2)
memory usage: 236.1+ KB