<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_ml/ml05_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

머신러닝(Machine Learning) 종류 - 사람의 감독 하에 훈련하는 것인 지 여부
*   지도학습(supervised learning): 레이블(타겟)이 있는 데이터를 학습.
    *   분류(classification): 클래스들을 분류.
    *   회귀(regression): 수치 예측.
*   비지도학습(unsupervised learning): 레이블이 없는 데이터를 학습.
    *   군집화(clustering)
    *   시각화(visualization)
*   준지도학습(semi-supervised learning): 비지도학습 + 전문가 시스템.

목표: fish 데이터셋에서 물고기의 무게(Weight) 예측.

*   농어(Perch)의 무게(Weight)를 길이(Length) 특성만으로 예측.
    *   Weight ~ Length
    *   무게(Weight): 관심 변수. 종속 변수. 레이블(label). 타겟(target).
    *   길이(Length): 독립 변수. 특성(feature).
    *   KNN, Linear Regression(선형 회귀) 모델을 비교.
*   농어의 무게를 다른 4개의 특성(Length, Diagonal, Height, Width)을 사용해서 예측.
    *   Weight ~ Length + Diagonal + Height + Width

# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler  # 표준화 특성 스케일링 변환기
from sklearn.preprocessing import PolynomialFeatures  # 다차항을 추가할 수 있는 변환기
from sklearn.pipeline import Pipeline  # 변환기와 추정기를 연결하는 클래스
from sklearn.neighbors import KNeighborsRegressor  # KNN 회귀 모델(추정기)
from sklearn.linear_model import LinearRegression  # 선형 회귀 모델(추정기)
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score  # 회귀 평가 지표

# Fish 데이터셋 준비

In [2]:
file_path = 'https://bit.ly/fish_csv_data'
# https://raw.githubusercontent.com/rickiepark/hg-mldl/master/fish.csv

In [3]:
fish = pd.read_csv(file_path)

In [4]:
fish.head()

  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [5]:
# 농어(Perch) 데이터만 선택
perch = fish[fish.Species == 'Perch']

In [6]:
perch.head()

   Species  Weight  Length  Diagonal  Height   Width
72   Perch     5.9     8.4       8.8  2.1120  1.4080
73   Perch    32.0    13.7      14.7  3.5280  1.9992
74   Perch    40.0    15.0      16.0  3.8240  2.4320
75   Perch    51.5    16.2      17.2  4.5924  2.6316
76   Perch    70.0    17.4      18.5  4.5880  2.9415

In [7]:
perch.describe()

            Weight     Length   Diagonal     Height      Width
count    56.000000  56.000000  56.000000  56.000000  56.000000
mean    382.239286  27.892857  29.571429   7.861870   4.745723
std     347.617717   9.021668   9.529509   2.878177   1.774626
min       5.900000   8.400000   8.800000   2.112000   1.408000
25%     120.000000  21.825000  23.325000   5.692500   3.525000
50%     207.500000  25.300000  26.750000   6.921800   4.154900
75%     692.500000  36.625000  39.075000  10.846500   6.448125
max    1100.000000  44.000000  46.600000  12.800200   8.142000

농어의 무게를 길이만으로 예측할 수 있을까?

*   특성(features) 배열: Length --> (n_samples, n_features) shape의 2차원 배열
*   타겟(target) 배열: Weight --> (n_samples,) shape의 1차원 배열

In [13]:
# 특성 배열
x = perch[['Length']].values
x.shape

(56, 1)

In [14]:
# 타겟 배열
y = perch.Weight.values
y.shape

(56,)